# Generated by Django 5.0.6 on 2024-07-09 18:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='authentication',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_pass_hash', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.TextField()),
                ('post_published_at', models.DateTimeField(auto_now_add=True)),
                ('post_last_modified', models.DateTimeField(auto_now=True)),
                ('post_slug', models.SlugField(max_length=175)),
                ('post_status', models.CharField(default='Published', max_length=15)),
                ('post_description', models.TextField(blank=True, null=True)),
                ('post_featured_img_path', models.CharField(blank=True, max_length=170, null=True)),
                ('post_categories', models.ManyToManyField(to='website.category')),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.user')),
                ('post_tags', models.ManyToManyField(to='website.tag')),
            ],
        ),
    ]
