# Generated by Django 5.0.6 on 2024-07-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_tag_authentication_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
