# Generated by Django 5.0.6 on 2024-07-09 18:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_user_name_authentication_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='pwd',
            fields=[
                ('pwd_id', models.AutoField(primary_key=True, serialize=False)),
                ('pwd_hash', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
        migrations.DeleteModel(
            name='authentication',
        ),
    ]
