# Generated by Django 5.0.6 on 2024-07-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_authentication_delete_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('Published', 'Published'), ('Archived', 'Archived'), ('Deleted', 'Deleted')], default='Published', max_length=15),
        ),
    ]
