# Generated by Django 5.0.6 on 2024-07-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_user_name_post_user_id_alter_post_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_categories',
            field=models.ManyToManyField(blank=True, to='website.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_tags',
            field=models.ManyToManyField(blank=True, to='website.tag'),
        ),
    ]
